Drop PyPy support
I'm now getting an RPython asserion failure on my Linux Jenkins:

    pypy runtests: commands[0] | python tests.py
    ....RPython traceback:
      File "pypy_module_cpyext_api_4.c", line 8805, in PyPyModule_GetDict
      File "pypy_module_cpyext_pyobject.c", line 112, in from_ref
    Fatal RPython error: AssertionError
    ERROR: InvocationError: '/var/lib/jenkins/jobs/mgp2pdf/workspace/.tox/pypy/bin/python tests.py'

If neither Travis nor Jenkins can handle ReportLab on pypy, who am I to
insist otherwise?

(Assuming it's ReportLab and not, say, Pillow -- but imgdiff's tests
work on pypy.)